POST http://127.0.0.1:8000/api/create-admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

{
    "user_id": 3,
    "group_id": 1
}
####
